input_dir: /Users/isabellechen/Desktop/phd/jarvis_lab/papers
output_dir: /Users/isabellechen/Desktop/phd/jarvis_lab
py_env: /Users/isabellechen/Library/Caches/pypoetry/virtualenvs/markdown-ZELfe5ZZ-py3.10/bin/activate